import "./globals.css";
import Navbar from "../ssg-components/Navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar
            hrefs={[
              { ref: "/", content: "Home" },
              { ref: "/", content: "About" },
              { ref: "/", content: "Contact" },
            ]}
          />
        </header>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
